export const POEMS = [
  'Epic nights, laughter in a blaze,\nJoyful memories woven, hearts in a daze.\nUnlock the fun, in jubilant craze.',
  "Unlock the fun, embrace the play,\nPlayrooms booked right, joyous array.\nTreasure the memories, forever they'll stay.",
  'Reserve your joyride, the night ignites,\nGame rooms booked right, excitement takes flight.\nEpic memories crafted, hearts soaring in delight.',
  'In joyful memories, we find our place,\nReserve for an epic night, where smiles embrace.\nUnfading joy, happiness we embrace.',
  'Epic nights, where dreams unfold,\nCherished memories, like treasures of gold.\nOne reservation at a time, a story to be told.',
  'Book the ultimate playtime, memories to keep,\nGame rooms reserved right, moments run deep.\nEndless fun, in our hearts, the memories leap.',
  "Unlock the fun, step into the game,\nPlayrooms booked right, joy's the aim.\nTreasure the memories, life will never be the same.",
  'Reserve your joyride, venture into the night,\nGame rooms booked right, fun takes its flight.\nEpic memories, laughter and delight, hearts alight.',
  'Reserve for an epic night, the magic begins,\nTreasure the memories, as each heart wins.\nUnfading joy, playrooms booked right in,\nEverlasting memories, in our souls within.',
  'Playful rooms, where happiness is found,\nCherished memories, our hearts surround.\nUnfading joy, our spirits unbound.',
  "PlayTime's magic, where memories bloom,\nEndless fun, laughter's sonic boom.\nTimeless moments, weaving memories' loom.",
  "In PlayTime's realm, joyrides take flight,\nGame nights made easy, stars shining bright.\nBooking ultimate playtime, hearts alight.",
  'The canvas of play, vivid and grand,\nJoyful memories crafted, hand in hand.\nUnlock the fun, in this enchanted land.',
  'Reserve for an epic night, memories take flight,\nA symphony of joy, a grand delight.\nIn this playtime haven, our spirits unite.',
  'In playful rooms, laughter reverberates,\nCherished moments, love creates.\nUnfading joy, where happiness elates.',
  'Epic nights unfold, an enchanting sight,\nEndless fun, hearts ignite.\nTimeless memories, like stars so bright.',
  'In the realm of joyrides, our story begins,\nGame nights made easy, where the adventure wins.\nBook the ultimate playtime, as the journey spins.',
  'Game nights made easy, our spirits rise,\nEverlasting memories, joy never dies.\nTreasure the moments, a euphoric sunrise.',
  "Reserve your joyride, in stars' array,\nCherishable memories, forever will sway.\nTimeless joy, like sunbeams that play.",
  "Reserve for PlayTime's epic night,\nA symphony of joy, hearts unite.\nIn this wonderland, happiness takes its height.",
  "Unlock the fun, with PlayTime's cheer,\nEverlasting memories, we hold dear.\nIn this play paradise, joy's atmosphere.",
  'Playful rooms, where memories are sown,\nBook the ultimate playtime, happiness sown.\nEpic nights, where joy is known.',
  "In PlayTime's embrace, dreams are born,\nEndless fun, hearts not torn.\nTimeless memories, cherished adorn.",
  "With PlayTime's charm, our spirits dance,\nIn playful rooms, laughter's expanse.\nUnlock the fun, in this enchanted trance.",
  "Embrace the moments, in PlayTime's glow,\nEverlasting memories, hearts aflow.\nIn this playground of joy, happiness we bestow.",
  "Unlock the fun, in PlayTime's domain,\nPlayrooms booked right, a joyous refrain.\nTreasure the memories, forever remain.",
  "PlayTime's wonders, where dreams ignite,\nCherished memories, like stars alight.\nUnfading joy, hearts take flight.",
  "PlayTime's nights, an anthem we sing,\nA chorus of fun, joy's evergreen.\nTogether we dance, in jubilant zing.",
  "With PlayTime, hearts bound in grace,\nCherishable memories, time can't erase.\nIn this magical realm, happiness we embrace.",
  "In PlayTime's embrace, laughter thrives,\nGame rooms booked right, fun derives.\nEpic nights, where joy survives.",
  'Playful realms, where friendships bloom,\nGame nights made easy, hearts consume.\nEpic memories, like a beautiful plume.',
  'Timeless joy, reserved for you,\nCherishable memories, forever true.\nBook the ultimate playtime, no ado,\nEndless fun, hearts anew.',
  "Reserve for PlayTime's mirthful delight,\nA night of wonders, hearts alight.\nIn this land of joy, spirits take flight.",
  "In PlayTime's magic, hearts align,\nEverlasting memories, like stars that shine.\nIn this joyful realm, life intertwine.",
  "PlayTime's delight, where giggles resound,\nCherished memories, love surrounds.\nUnfading joy, forever profound.",
  "With PlayTime's wonder, we unite,\nGame rooms booked right, spirits take flight.\nTimeless memories, in joy's spotlight.",
  "Unlock the laughter, in PlayTime's care,\nBook the ultimate playtime, memories we share.\nIn this haven of joy, hearts declare.",
  "PlayTime's symphony, where happiness gleams,\nEpic nights unfold, like vibrant dreams.\nIn this world of play, joy redeems.",
  "Embrace the magic, in PlayTime's grace,\nPlayrooms booked right, smiles we embrace.\nTreasure the memories, love we trace.",
  'Playful rooms, where delights unite,\nCherished memories, like stars at night.\nUnfading joy, hearts feel light.',
  "In PlayTime's realm, memories awake,\nEndless fun, dreams we make.\nTimeless memories, moments we partake.",
  'Unfading joy, cherished memories,\nEmbrace the fun, with ease and ease.\nEndless playtime, time to seize,\nUltimate game nights, joy unleashed.',
  'Reserve your joyride, seize the night,\nGame rooms booked right, pure delight.\nEpic nights, endless fun in sight,\nTreasure memories, hearts ignite.',
  "Reserve your joyride, a night to cherish,\nGame rooms booked right, the fun won't perish.\nEpic memories unfold, happiness will flourish,\nEndless fun, timeless joy, forever to nourish.",
  "Reserve for an epic night, make memories divine,\nGame rooms, playrooms, laughter entwined.\nEndless fun, where hearts align,\nCherished moments, life's grand design.",
  'Memories to treasure, joyride unfold,\nGame nights made easy, stories retold.\nEpic nights, where hearts are bold,\nCherished moments, pure gold.',
  'Unleash the fun, let laughter resound,\nEpic nights, where memories abound.\nGame rooms, playrooms, adventure unwound,\nCherish the moments, happiness compound.',
  'Unlock the joy, reserve with glee,\nCherished memories, let them be.\nGame nights made easy, come and see,\nEpic nights ahead, full of gaiety.',
  'Endless fun, timeless nights,\nBook your joyride, take to the heights.\nGame rooms, just right, in radiant lights,\nEpic memories, pure delights.',
  "Joyrides to treasure, playtime grand,\nEpic nights and memories hand in hand.\nReserve the fun, take a stand,\nCherish the moments, life's finest strand.",
  'Game rooms set right, playrooms abound, Treasured delight, joy all around. Embrace the night, memories found, Epic nights forever, in happiness bound.',
];
